COORDINATOR = "coordinator"
ROUTING = "routing"
SOURCING_QUALITY = "sourcing_quality"
IMPROVEMENT_ACTION = "improvement_action"
RESOURCE_OPTIMIZATION = "resource_optimization"
OFFER_INSIGHTS = "offer_insights"
PIPELINE_HEALTH = "pipeline_health"
EVALUATION = "evaluation"
OPTIMIZATION = "optimization"

ALL_AGENTS = [
    COORDINATOR,
    ROUTING,
    SOURCING_QUALITY,
    IMPROVEMENT_ACTION,
    RESOURCE_OPTIMIZATION,
    OFFER_INSIGHTS,
    PIPELINE_HEALTH,
    EVALUATION,
    OPTIMIZATION,
]

INSIGHT_AGENTS = [
    SOURCING_QUALITY,
    IMPROVEMENT_ACTION,
    RESOURCE_OPTIMIZATION,
    OFFER_INSIGHTS,
    PIPELINE_HEALTH,
]

SUPPORT_AGENTS = [EVALUATION, OPTIMIZATION]
