"""initial_schema

Revision ID: 0b733d068c30
Revises: 
Create Date: 2026-05-16 11:39:10.043990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b733d068c30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_channel', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('experience_years', sa.Float(), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=False),
    sa.Column('overall_status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ats'
    )
    op.create_table('interviewers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='ats'
    )
    op.create_table('interview_stages',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('interviewer_id', sa.Uuid(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['ats.candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interviewer_id'], ['ats.interviewers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='ats'
    )
    op.create_table('offers',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('salary_offered', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('offered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['ats.candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ats'
    )
    op.create_table('rejections',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=False),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason_category', sa.String(), nullable=False),
    sa.Column('reason_detail', sa.String(), nullable=True),
    sa.Column('rejected_by_interviewer_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['ats.candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rejected_by_interviewer_id'], ['ats.interviewers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='ats'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rejections', schema='ats')
    op.drop_table('offers', schema='ats')
    op.drop_table('interview_stages', schema='ats')
    op.drop_table('interviewers', schema='ats')
    op.drop_table('candidates', schema='ats')
    # ### end Alembic commands ###
